apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Workflow
on:
  push:
    branches:
      - "**"
env:
  APP_NAME: java-app
  UNIQUE_PREFIX: sw
  
jobs:
  build-and-publish:
    steps:
      - uses: cloudbees-io/checkout@v1
        name: Checkout
      - uses: docker://maven:3.9.6-eclipse-temurin-17
        name: Build JAR
        shell: sh
        run: |
          mvn clean install
      - uses: docker://golang:1.20.3-alpine3.17
        name: Show built files in target dir
        shell: sh
        run: |
          find ./target
      - uses: cloudbees-io/configure-aws-credentials@v1
        id: aws-login
        name: configure AWS credentials
        with:
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-access-key-id: ${{ vars.aws_access_key_id }}
          aws-region: us-east-1
          role-to-assume: cloudbees-infra-mgmt
          role-duration-seconds: "3600"
      - uses: docker://public.ecr.aws/aws-cli/aws-cli
        name: AWS CLI Testing
        run: |-
          set -x
          aws sts get-caller-identity
          aws s3 ls
        shell: sh
      - uses: cloudbees-io/configure-ecr-credentials@v1
        name: Configure ECR
      - uses: cloudbees-io/kaniko@v1
        name: Build and Publish Container Image
        id: image-publish
        with:
          destination: ${{ steps.aws-login.outputs.aws-account-id
            }}.dkr.ecr.us-east-1.amazonaws.com/${{ env.APP_NAME }}-image:${{
            env.UNIQUE_PREFIX }}-${{ cloudbees.version }}
