apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Workflow
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - uses: cloudbees-io/checkout@v1
        name: Checkout
      - uses: docker://maven:3.9.6-eclipse-temurin-17
        name: Build JAR
        shell: sh
        run: |
          mvn clean install
      - uses: docker://golang:1.20.3-alpine3.17
        name: Show built files in target dir
        shell: sh
        run: |
          find ./target
      - uses: cloudbees-io/configure-aws-credentials@v1
        name: configure AWS credentials
        with:
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-access-key-id: ${{ vars.aws_access_key_id }}
          aws-region: us-east-1
          role-to-assume: cloudbees-infra-mgmt
          role-duration-seconds: "3600"
      - uses: docker://public.ecr.aws/aws-cli/aws-cli
        name: Publish to ECR
        run: |-
          set -x
          aws sts get-caller-identity
          aws s3 ls
        shell: sh
